import './globals.css'
import { HistoryProvider } from './context'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <HistoryProvider>
        <body>{children}</body>
      </HistoryProvider>
    </html>
  )
}
